import { Roboto } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import Link from "next/link";
import { useContext } from "react";

const roboto = Roboto({
  weight: "400",
  variable: "--font-roboto",
  subsets: ["latin"],
});


export const metadata = {
  title: "Contact List",
  description: "Generated by create next app",
};

const contactContextvalue = {
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} bg-dark`}>{children}</body>
    </html>
  );
}
